jsxSingleQuote: true
plugins: ["prettier-plugin-tailwindcss"]
printWidth: 160
semi: false
singleQuote: true
tabWidth: 2
# tailwindStylesheet: "./src/assets/main.css"
trailingComma: none
useTabs: false
